
```py
>>> c2,c3,q1p,q2p,c1,s1,s2,s3= symbols('c2 c3 q1p q2p c1 s1 s2 s3')

>>> test=c2**2*q2p*c3 + c1**2*s2**2*q2p*c3 + s1**2*s2**2*q2p*c3 -
c1**2*q1p*c2*s3 - s1**2*q1p*c2*s3

>>> test.subs({c1**2 : 1-s1**2, c2**2 : 1-s2**2, c3**3: 1-s3**2})

ERROR: An unexpected error occurred while tokenizing input           
The following traceback may be corrupted or invalid                  
The error message is: ('EOF in multi-line statement', (22, 0))       

ERROR: An unexpected error occurred while tokenizing input
The following traceback may be corrupted or invalid       
The error message is: ('EOF in multi-line statement', (96, 0))
```

